import { $, FRI, SAT, type SeedModifierGroup } from "./types";

const COWBOY_MEATS = [
  { name: "Brisket", price: $(2) },
  { name: "Pulled Pork" },
  { name: "House Sausage" },
  { name: "Smoked Turkey" },
  { name: "Pork Spare Ribs", note: "Fri & Sat only", days: [FRI, SAT] },
  { name: "Pork Belly Burnt Ends", note: "Fri & Sat only", days: [FRI, SAT] },
];

const TACO_FILLINGS = [
  { name: "Carnitas" },
  { name: "Chorizo" },
  { name: "Chicken" },
  { name: "Taco de Papas", dietary: ["vegetarian" as const] },
  { name: "Tofu", dietary: ["vegetarian" as const] },
  { name: "Pork Belly", price: $(1), note: "+$1 per taco · Fri & Sat only", days: [FRI, SAT] },
];

export const MODIFIER_GROUPS: SeedModifierGroup[] = [
  /* ---------- Breakfast ---------- */
  {
    key: "breakfast_grill_addons",
    name: "Add to any grill item",
    min: 0,
    max: 9,
    modifiers: [
      { name: "Bacon", price: $(3) },
      { name: "Pulled Pork", price: $(3) },
      { name: "Smoked Chicken", price: $(3) },
      { name: "Chorizo", price: $(4) },
      { name: "Suadero", price: $(3) },
      { name: "Avocado", price: $(2) },
      { name: "Refried Beans", price: $(1) },
      { name: "Pickled Red Onions", price: 75 },
      { name: "Hatch Chile Cream Cheese", price: $(1) },
    ],
  },
  {
    key: "bread_choice",
    name: "Choice of Bread",
    required: true,
    min: 1,
    max: 1,
    modifiers: [
      { name: "Everything Bagel", dietary: ["vegan"] },
      { name: "Housemade Biscuit" },
      { name: "Texas Toast" },
      { name: "Potato Bun" },
    ],
  },
  {
    key: "avocado_base",
    name: "Bagel or Toast",
    required: true,
    min: 1,
    max: 1,
    modifiers: [{ name: "Everything Bagel" }, { name: "Toast" }],
  },
  {
    key: "spreads",
    name: "Spreads",
    min: 0,
    max: 5,
    modifiers: [
      { name: "Cream Cheese", price: $(2) },
      { name: "Hatch Chile Cream Cheese", price: $(2) },
      { name: "Peanut Butter", price: $(2) },
      { name: "House Jam", price: $(2), dietary: ["vegan"] },
      { name: "Butter", price: $(2) },
    ],
  },

  /* ---------- Craft Barbecue ---------- */
  {
    key: "cowboy_meat_1",
    name: "Choose Your Meat",
    required: true,
    min: 1,
    max: 1,
    modifiers: COWBOY_MEATS,
  },
  {
    key: "cowboy_meat_2",
    name: "Choose Two Meats",
    required: true,
    min: 2,
    max: 2,
    modifiers: COWBOY_MEATS,
  },
  {
    key: "cowboy_addons",
    name: "Plate Add-ons",
    min: 0,
    max: 2,
    modifiers: [
      { name: "Add Corn Bread", price: $(1) },
      { name: "Add a Side", price: $(4) },
    ],
  },
  {
    key: "top_it_sandwich",
    name: "Top It!",
    required: true,
    min: 1,
    max: 1,
    modifiers: [
      { name: "Top It! #1", description: "tejano slaw & sauce" },
      { name: "Top It! #2", description: "pickles, pickled red onions & sauce" },
    ],
  },
  {
    key: "wings_dip",
    name: "Ranch or Bleu Cheese",
    required: true,
    min: 1,
    max: 1,
    modifiers: [{ name: "Ranch" }, { name: "Bleu Cheese" }],
  },
  {
    key: "wings_vegan",
    name: "Vegan Option",
    min: 0,
    max: 1,
    modifiers: [{ name: "Sub Fried Tofu", description: "Vegan substitute for wings", dietary: ["vegan"] }],
  },
  {
    key: "nacho_protein",
    name: "Choose Your Protein",
    required: true,
    min: 1,
    max: 1,
    modifiers: [
      { name: "Chicken" },
      { name: "Pulled Pork" },
      { name: "Bean", dietary: ["vegetarian"] },
      { name: "Chorizo", price: $(3) },
      { name: "Brisket", price: $(6) },
    ],
  },
  {
    key: "taco_filling_1",
    name: "Choose Your Filling",
    required: true,
    min: 1,
    max: 1,
    modifiers: TACO_FILLINGS,
  },
  {
    key: "taco_filling_3",
    name: "Choose Your Fillings",
    description: "Pick up to 3 fillings for your 3 tacos",
    required: true,
    min: 1,
    max: 3,
    modifiers: TACO_FILLINGS,
  },
  {
    key: "top_it_taco",
    name: "Top It!",
    required: true,
    min: 1,
    max: 1,
    modifiers: [
      { name: "Top It! #1", description: "slaw, verde, crema, cheese" },
      { name: "Top It! #2", description: "beans, verde, onion-cilantro" },
    ],
  },
  {
    key: "flight_dips",
    name: "Choose 3 Dips",
    required: true,
    min: 3,
    max: 3,
    modifiers: [
      { name: "Queso" },
      { name: "Guacamole", dietary: ["vegan"] },
      { name: "Refried Beans", dietary: ["vegan"] },
      { name: "Salsa Roja", dietary: ["vegan"] },
    ],
  },

  /* ---------- Sunday Brunch ---------- */
  {
    key: "brunch_add_egg",
    name: "Add Egg",
    min: 0,
    max: 1,
    modifiers: [{ name: "Add Egg", price: $(3) }],
  },
  {
    key: "burrito_addins",
    name: "Add-ins (inside)",
    min: 0,
    max: 5,
    modifiers: [
      { name: "Brisket", price: $(5) },
      { name: "Chorizo", price: $(3) },
      { name: "Pulled Pork", price: $(3) },
      { name: "Pork Belly", price: $(4) },
      { name: "Bacon", price: $(3) },
    ],
  },
  {
    key: "burrito_addons",
    name: "Add-ons (on top)",
    min: 0,
    max: 6,
    modifiers: [
      { name: "Queso", price: $(3) },
      { name: "Ranchero Sauce", price: $(3) },
      { name: "Guacamole", price: $(4) },
      { name: "Sausage Gravy", price: $(4) },
      { name: "Salsa Roja", price: $(3) },
      { name: "Over Medium Egg", price: $(3) },
    ],
  },
  {
    key: "breakfast_nacho_addons",
    name: "Breakfast Nachos Add-ons",
    min: 0,
    max: 6,
    modifiers: [
      { name: "Brisket", price: $(7) },
      { name: "Pulled Pork", price: $(5) },
      { name: "Bacon", price: $(5) },
      { name: "Chorizo", price: $(5) },
      { name: "Pork Belly", price: $(6) },
      { name: "Fried Tofu", price: $(5), dietary: ["vegan"] },
    ],
  },
  {
    key: "pancake_style",
    name: "Savory or Sweet",
    required: true,
    min: 1,
    max: 1,
    modifiers: [
      { name: "Savory", description: "chile-bacon jam" },
      { name: "Sweet", description: "cactus honey 'n berry", dietary: ["vegetarian"] },
    ],
  },
  {
    key: "pancake_addons",
    name: "Pancake Add-ons",
    min: 0,
    max: 5,
    modifiers: [
      { name: "Side Egg", price: $(3) },
      { name: "Side Bacon", price: $(4) },
      { name: "Side Potatoes", price: $(5) },
      { name: "Whip", price: $(1) },
      { name: "Sprinkles", price: $(1) },
    ],
  },
  {
    key: "bloody_spirit",
    name: "Vodka or Tequila",
    required: true,
    min: 1,
    max: 1,
    modifiers: [{ name: "Vodka" }, { name: "Tequila" }],
  },
  {
    key: "pitcher_style",
    name: "Mimosa or Bloody",
    required: true,
    min: 1,
    max: 1,
    modifiers: [{ name: "Mimosa" }, { name: "Bloody" }],
  },

  /* ---------- Bar ---------- */
  {
    key: "coors_bourbon",
    name: "Add a Shot",
    min: 0,
    max: 1,
    modifiers: [{ name: "Add Bourbon", price: $(3), description: "with Coors Banquet" }],
  },
  {
    key: "tecate_tequila",
    name: "Add a Shot",
    min: 0,
    max: 1,
    modifiers: [{ name: "Add Tequila", price: $(3), description: "with Tecate" }],
  },

  /* ---------- Cafe ---------- */
  {
    key: "drink_options",
    name: "Options",
    min: 0,
    max: 6,
    modifiers: [
      { name: "Oat Milk", price: 90 },
      { name: "Almond Milk", price: 90 },
      { name: "Syrup", price: 80 },
      { name: "Sauce", price: 115 },
      { name: "Extra Espresso Shot (+1)", price: 150 },
      { name: "Housemade Syrup", price: 125 },
    ],
  },
  {
    key: "milk_chocolate",
    name: "Make it Chocolate",
    min: 0,
    max: 1,
    modifiers: [{ name: "Chocolate", price: $(1) }],
  },
];
